version: '3.8'

services:
  # 1. Container Database MySQL
  db:
    image: mysql:8.0
    container_name: growsafe_mysql
    restart: always
    environment:
      MYSQL_DATABASE: growsafe_db
      MYSQL_ROOT_PASSWORD: rootpassword # Ganti dengan password root pilihanmu
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. Container Backend FastAPI
  backend:
    build: .
    container_name: growsafe_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_HOST=db  # PENTING: Namanya harus 'db', bukan 'localhost'
      - DB_NAME=growsafe_db

volumes:
  mysql_data: # Untuk menyimpan data database agar tidak hilang saat docker dimatikan